version = 0.1

[default.deploy.parameters]
stack_name = "customer-care-ai-dev"
resolve_s3 = true
s3_prefix = "customer-care-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[dev.deploy.parameters]
stack_name = "customer-care-ai-dev"
parameter_overrides = "Environment=dev"

[staging.deploy.parameters]
stack_name = "customer-care-ai-staging"
parameter_overrides = "Environment=staging"

[prod.deploy.parameters]
stack_name = "customer-care-ai-prod"
parameter_overrides = "Environment=prod"
confirm_changeset = true
